In [83]:
#libraries
import pandas as pd
import numpy as np
import pyodbc, sys, os
from imp import reload
pyodbc.autocommit = True

In [84]:
#Connecting to Datalake
conn = pyodbc.connect("DSN=DXC_Prod",driver='SQLDriverConnect',autocommit=True)

In [ ]:
#scm_rpt.rpt_pwr_bi_po_dtls_vw table
df_EDL=pd.read_sql("select * from scm_rpt.rpt_pwr_bi_po_dtls_vw", conn)

In [4]:
df_EDL

,rpt_pwr_bi_po_dtls_vw.fscl_mth_nm,rpt_pwr_bi_po_dtls_vw.fscl_qtr_nm,rpt_pwr_bi_po_dtls_vw.fscl_yr_nm,rpt_pwr_bi_po_dtls_vw.lg_dn,rpt_pwr_bi_po_dtls_vw.cst_cntr_cd,rpt_pwr_bi_po_dtls_vw.pft_cntr_cd,rpt_pwr_bi_po_dtls_vw.shrt_dn,rpt_pwr_bi_po_dtls_vw.mgr_nm,rpt_pwr_bi_po_dtls_vw.mgr_eml_addr_txt,rpt_pwr_bi_po_dtls_vw.prod_atr_1_cd,...,rpt_pwr_bi_po_dtls_vw.ord_end_dt_ky,rpt_pwr_bi_po_dtls_vw.cust_nr,rpt_pwr_bi_po_dtls_vw.cust_nm,rpt_pwr_bi_po_dtls_vw.proc_type,rpt_pwr_bi_po_dtls_vw.class_l_m,rpt_pwr_bi_po_dtls_vw.gr_ind,rpt_pwr_bi_po_dtls_vw.ln_itm_totl_lcl_curr_amt,rpt_pwr_bi_po_dtls_vw.ln_itm_totl_usd_amt,rpt_pwr_bi_po_dtls_vw.spnd_amt,rpt_pwr_bi_po_dtls_vw.rvgn_cmpss_flg
0,2019-M11,2019-Q4,2019,ES 6N EMEA Consult AE,AEET500135,P1523,AE00002875,"Preda-Saftoiu,Loredana-Cristina",loredana-cristina.saftoiu@dxc.com,None,...,None,,,None,None,None,2800.00,3637.31,0.00,N
1,2019-M11,2019-Q4,2019,FSM-SKF-6N,FRET505289,P1410,FR40010365,"Olteanu,Mihail",mihail.olteanu@dxc.com,None,...,None,,,None,None,None,11.33,13.00,376.37,Y
2,2019-M11,2019-Q4,2019,JCI UK Intercompany..,GBA5030380,P2007,JCI UK Intercompany,"Loureiro,Ivan",ivan.loureiro@dxc.com,None,...,None,,,None,None,None,657.35,864.41,0.00,Y
3,2019-M11,2019-Q4,2019,RCC ES LC 40000865 6N00,AUES501517,P1634,AU00008515,"Agarwalla,Shyam",sagarwalla4@dxc.com,None,...,None,,,None,None,None,1815.44,1323.49,1323.50,Y
4,2019-M11,2019-Q4,2019,RCC ES LC 6N 9539 Adient,DEET506548,P2007,DE50501317,"Hutchinson,Andrea",andrea.hutchinson@dxc.com,None,...,None,,,None,None,None,1037.68,1190.74,0.00,Y
5,2019-M11,2019-Q4,2019,RCC ES LC 6N00 SKF.,USA7138956,P1410,RCC ES LC 6N00 SKF,"Olteanu,Mihail",mihail.olteanu@dxc.com,None,...,None,,,None,None,None,533.98,533.98,0.00,Y
6,2019-M11,2019-Q4,2019,"Sao Bernardo do Campo, SP - EDS (SBB)",BR50001919,P1756,Sao Bernardo do Camp,"Labrador,Steve",stephen.j.labrador@dxc.com,None,...,None,,,None,None,None,4479.84,1086.55,0.00,N
7,2019-M11,2019-Q4,2019,Unclassified,,,,,,43210000,...,None,None,None,None,None,X,2662.50,3502.39,4192.27,N
8,2019-M11,2019-Q4,2019,Unclassified,,,,,,83110000,...,None,PRCENTER,Profitcenter,CB,None,X,38100.00,38100.00,42815.72,N
9,2019-M12,2019-Q4,2019,ES G6 Mirror for INES,AUES509639,P2047,ES G6 Mirror for IN,"JAIN,VISHAL",vishal.jain@dxc.com,None,...,None,,,None,None,None,458.16,330.80,0.00,N

In [5]:
df.columns

Index(['rpt_pwr_bi_po_dtls_vw.fscl_mth_nm',
       'rpt_pwr_bi_po_dtls_vw.fscl_qtr_nm', 'rpt_pwr_bi_po_dtls_vw.fscl_yr_nm',
       'rpt_pwr_bi_po_dtls_vw.lg_dn', 'rpt_pwr_bi_po_dtls_vw.cst_cntr_cd',
       'rpt_pwr_bi_po_dtls_vw.pft_cntr_cd', 'rpt_pwr_bi_po_dtls_vw.shrt_dn',
       'rpt_pwr_bi_po_dtls_vw.mgr_nm',
       'rpt_pwr_bi_po_dtls_vw.mgr_eml_addr_txt',
       'rpt_pwr_bi_po_dtls_vw.prod_atr_1_cd',
       'rpt_pwr_bi_po_dtls_vw.prod_atr_6_cd',
       'rpt_pwr_bi_po_dtls_vw.prod_atr_4_nm',
       'rpt_pwr_bi_po_dtls_vw.prod_atr_3_nm', 'rpt_pwr_bi_po_dtls_vw.prod_nr',
       'rpt_pwr_bi_po_dtls_vw.prod_dn', 'rpt_pwr_bi_po_dtls_vw.prod_atr_1_nm',
       'rpt_pwr_bi_po_dtls_vw.cst_cntr_nr', 'rpt_pwr_bi_po_dtls_vw.ctry_cd',
       'rpt_pwr_bi_po_dtls_vw.cst_ctry_nm', 'rpt_pwr_bi_po_dtls_vw.co_cd',
       'rpt_pwr_bi_po_dtls_vw.rptg_typ_nm',
       'rpt_pwr_bi_po_dtls_vw.pstg_obj_id',
       'rpt_pwr_bi_po_dtls_vw.gsap_pft_cntr_nm',
       'rpt_pwr_bi_po_dtls_vw.mgmt_wbs_cd', 'rpt_pwr_bi_po_dtls_vw.clnt_id',
       'rpt_pwr_bi_po_dtls_vw.clnt_nm',
       'rpt_pwr_bi_po_dtls_vw.dxcmh_nde_l2_dn',
       'rpt_pwr_bi_po_dtls_vw.dxcmh_nde_l3_dn',
       'rpt_pwr_bi_po_dtls_vw.dxcmh_nde_l4_dn',
       'rpt_pwr_bi_po_dtls_vw.dxcmh_nde_l5_dn',
       'rpt_pwr_bi_po_dtls_vw.dxcmh_nde_l6_dn',
       'rpt_pwr_bi_po_dtls_vw.dxcmh_pstg_objs_grp_9_dn',
       'rpt_pwr_bi_po_dtls_vw.fnl_pstg_obj_cd',
       'rpt_pwr_bi_po_dtls_vw.pstg_obj_nm',
       'rpt_pwr_bi_po_dtls_vw.mjr_ofrng_cd',
       'rpt_pwr_bi_po_dtls_vw.bsn_dfnd_fld_2_nm',
       'rpt_pwr_bi_po_dtls_vw.bsn_dfnd_fld_4_nm',
       'rpt_pwr_bi_po_dtls_vw.cst_stack_grp_acct_lvl6_nm',
       'rpt_pwr_bi_po_dtls_vw.cst_stack_grp_acct_lvl7_nm',
       'rpt_pwr_bi_po_dtls_vw.cst_stack_grp_acct_lvl8_nm',
       'rpt_pwr_bi_po_dtls_vw.cst_stack_grp_acct_lvl9_nm',
       'rpt_pwr_bi_po_dtls_vw.wbs_cd', 'rpt_pwr_bi_po_dtls_vw.wbs_dn',
       'rpt_pwr_bi_po_dtls_vw.wbs_atr_1_cd',
       'rpt_pwr_bi_po_dtls_vw.gl_acct_dn', 'rpt_pwr_bi_po_dtls_vw.gl_acct_nr',
       'rpt_pwr_bi_po_dtls_vw.vndr_nr', 'rpt_pwr_bi_po_dtls_vw.vndr_ctry_nm',
       'rpt_pwr_bi_po_dtls_vw.splyr_nm', 'rpt_pwr_bi_po_dtls_vw.splyr_tr_cd',
       'rpt_pwr_bi_po_dtls_vw.gutm_bsn_nm', 'rpt_pwr_bi_po_dtls_vw.vndr_nm',
       'rpt_pwr_bi_po_dtls_vw.po_nr', 'rpt_pwr_bi_po_dtls_vw.lcl_curr_cd',
       'rpt_pwr_bi_po_dtls_vw.pmnt_trm_cd', 'rpt_pwr_bi_po_dtls_vw.porg_cd',
       'rpt_pwr_bi_po_dtls_vw.prch_grp_nm', 'rpt_pwr_bi_po_dtls_vw.po_vndr_nm',
       'rpt_pwr_bi_po_dtls_vw.itm_dn', 'rpt_pwr_bi_po_dtls_vw.po_ln_itm',
       'rpt_pwr_bi_po_dtls_vw.is_adhoc_flg', 'rpt_pwr_bi_po_dtls_vw.stts_nm',
       'rpt_pwr_bi_po_dtls_vw.exact_typ_cd', 'rpt_pwr_bi_po_dtls_vw.src_id',
       'rpt_pwr_bi_po_dtls_vw.src_nm', 'rpt_pwr_bi_po_dtls_vw.ky_po_dt',
       'rpt_pwr_bi_po_dtls_vw.ord_strt_dt', 'rpt_pwr_bi_po_dtls_vw.ord_end_dt',
       'rpt_pwr_bi_po_dtls_vw.po_dcmt_dt', 'rpt_pwr_bi_po_dtls_vw.po_crt_dt',
       'rpt_pwr_bi_po_dtls_vw.requisitioner_emp_ky',
       'rpt_pwr_bi_po_dtls_vw.requisitioner_usr_id',
       'rpt_pwr_bi_po_dtls_vw.preprr_emp_ky',
       'rpt_pwr_bi_po_dtls_vw.preprr_usr_id',
       'rpt_pwr_bi_po_dtls_vw.reqstr_emp_ky',
       'rpt_pwr_bi_po_dtls_vw.rqstr_usr_id',
       'rpt_pwr_bi_po_dtls_vw.prchg_splyr_nm',
       'rpt_pwr_bi_po_dtls_vw.ord_strt_dt_ky',
       'rpt_pwr_bi_po_dtls_vw.ord_end_dt_ky', 'rpt_pwr_bi_po_dtls_vw.cust_nr',
       'rpt_pwr_bi_po_dtls_vw.cust_nm', 'rpt_pwr_bi_po_dtls_vw.proc_type',
       'rpt_pwr_bi_po_dtls_vw.class_l_m', 'rpt_pwr_bi_po_dtls_vw.gr_ind',
       'rpt_pwr_bi_po_dtls_vw.ln_itm_totl_lcl_curr_amt',
       'rpt_pwr_bi_po_dtls_vw.ln_itm_totl_usd_amt',
       'rpt_pwr_bi_po_dtls_vw.spnd_amt',
       'rpt_pwr_bi_po_dtls_vw.rvgn_cmpss_flg'],
      dtype='object')

In [7]:
#scm_imt.imt_c1_po table
df1=pd.read_sql("select top 10 * from scm_imt.imt_c1_po", conn)
df1.columns

Index(['imt_c1_po.purchasing_doc', 'imt_c1_po.company_code',
       'imt_c1_po.created_on', 'imt_c1_po.currency', 'imt_c1_po.payt_terms',
       'imt_c1_po.purchasing_org', 'imt_c1_po.purch_group', 'imt_c1_po.vendor',
       'imt_c1_po.document_date', 'imt_c1_po.item', 'imt_c1_po.acct_assgt_cat',
       'imt_c1_po.deletion_ind', 'imt_c1_po.item_category',
       'imt_c1_po.changed_on', 'imt_c1_po.requisitioner', 'imt_c1_po.material',
       'imt_c1_po.mfr_part_number', 'imt_c1_po.material_group',
       'imt_c1_po.short_text', 'imt_c1_po.net_price', 'imt_c1_po.net_value',
       'imt_c1_po.validity_end_date', 'imt_c1_po.validity_start_date',
       'imt_c1_po.po_quantity', 'imt_c1_po.usd_net_order_price',
       'imt_c1_po.usd_net_order_value', 'imt_c1_po.order_unit',
       'imt_c1_po.price_unit', 'imt_c1_po.is_ad_hoc', 'imt_c1_po.wbs_element',
       'imt_c1_po.cost_center', 'imt_c1_po.co_area', 'imt_c1_po.g_l_account',
       'imt_c1_po.profit_center', 'imt_c1_po.asset', 'imt_c1_po.subnumber',
       'imt_c1_po.plant', 'imt_c1_po.edl_crt_ts', 'imt_c1_po.edl_upd_ts',
       'imt_c1_po.edl_src_sys_ky', 'imt_c1_po.edl_upd_tm_ky',
       'imt_c1_po.fl_nm', 'imt_c1_po.edl_chcksm_tx',
       'imt_c1_po.edl_job_sqn_nr'],
      dtype='object')

In [11]:
df1

,imt_c1_po.purchasing_doc,imt_c1_po.company_code,imt_c1_po.created_on,imt_c1_po.currency,imt_c1_po.payt_terms,imt_c1_po.purchasing_org,imt_c1_po.purch_group,imt_c1_po.vendor,imt_c1_po.document_date,imt_c1_po.item,...,imt_c1_po.asset,imt_c1_po.subnumber,imt_c1_po.plant,imt_c1_po.edl_crt_ts,imt_c1_po.edl_upd_ts,imt_c1_po.edl_src_sys_ky,imt_c1_po.edl_upd_tm_ky,imt_c1_po.fl_nm,imt_c1_po.edl_chcksm_tx,imt_c1_po.edl_job_sqn_nr
0,8500105063,1571,01/02/2019,USD,NN00,1571,105,0000110380,01/02/2019,00010,...,,,1571,2019-01-22 09:13:31,2019-01-23 02:59:08.829,999,20200905114045,C1_SCM_PO_20190122091331.csv,,1
1,8500105064,1453,01/02/2019,USD,NN30,1453,105,0000112626,01/02/2019,00010,...,,,1453,2019-01-22 09:13:31,2019-01-23 02:59:08.829,999,20200905114045,C1_SCM_PO_20190122091331.csv,,1
2,8500105065,1453,01/02/2019,USD,NN60,1453,105,0000112806,01/02/2019,00010,...,,,1453,2019-01-22 09:13:31,2019-01-23 02:59:08.829,999,20200905114045,C1_SCM_PO_20190122091331.csv,,1
3,8500105066,1453,01/02/2019,USD,NN60,1453,105,0000112806,01/02/2019,00010,...,,,1453,2019-01-22 09:13:31,2019-01-23 02:59:08.829,999,20200905114045,C1_SCM_PO_20190122091331.csv,,1
4,8500105067,1453,01/02/2019,USD,NN30,1453,105,0000112716,01/02/2019,00010,...,,,1453,2019-01-22 09:13:31,2019-01-23 02:59:08.829,999,20200905114045,C1_SCM_PO_20190122091331.csv,,1
5,8500105068,1453,01/02/2019,USD,NN60,1453,105,0000112806,01/02/2019,00010,...,,,1453,2019-01-22 09:13:31,2019-01-23 02:59:08.829,999,20200905114045,C1_SCM_PO_20190122091331.csv,,1
6,8500105069,1453,01/02/2019,USD,NN60,1453,105,0000112806,01/02/2019,00010,...,,,1453,2019-01-22 09:13:31,2019-01-23 02:59:08.829,999,20200905114045,C1_SCM_PO_20190122091331.csv,,1
7,8500105070,1453,01/02/2019,USD,NN60,1453,105,0000112806,01/02/2019,00010,...,,,1453,2019-01-22 09:13:31,2019-01-23 02:59:08.829,999,20200905114045,C1_SCM_PO_20190122091331.csv,,1
8,8500105071,1201,01/02/2019,USD,NN60,1201,103,0000910228,01/02/2019,00010,...,,,1201,2019-01-22 09:13:31,2019-01-23 02:59:08.829,999,20200905114045,C1_SCM_PO_20190122091331.csv,,1
9,8500105071,1201,01/02/2019,USD,NN60,1201,103,0000910228,01/02/2019,00020,...,,,1201,2019-01-22 09:13:31,2019-01-23 02:59:08.829,999,20200905114045,C1_SCM_PO_20190122091331.csv,,1

In [8]:
# Joining tables

In [85]:
%%time
#imt_c1_po.purchasing_doc
#df_final=pd.read_sql('''Select rpt.po_nr,rpt.cst_cntr_nr, rpt.po_ln_itm, rpt.cst_cntr_cd, rpt.co_cd,rpt.fscl_mth_nm,rpt.fscl_yr_nm,rpt.fscl_qtr_nm,rpt.ky_po_dt,c1.company_code, c1.item,
#c1.cost_center,c1.created_on,c1.requisitioner,c1.wbs_element,c1.g_l_account,c1.profit_center
#From scm_rpt.rpt_pwr_bi_po_dtls_vw rpt
#inner join (select distinct purchasing_doc, company_code, item, cost_center,created_on,requisitioner,wbs_element,g_l_account,profit_center from scm_imt.imt_c1_po) c1
#on rpt.po_nr = c1.purchasing_doc
#and rpt.po_ln_itm = c1.item
#where rpt.fscl_yr_nm in ('2021', '2022')''', conn)
df_final= pd.read_sql('''WITH ranked_imt_c1 AS (
SELECT c1_imt.*, ROW_NUMBER() OVER (PARTITION BY c1_imt.purchasing_doc, c1_imt.item ORDER BY edl_job_sqn_nr DESC) AS rn
FROM scm_imt.imt_c1_po AS c1_imt
)
Select rpt.ky_po_dt, rpt.cst_cntr_nr, rpt.po_nr, rpt.po_ln_itm, rpt.stts_nm, rpt.cst_cntr_cd, rpt.co_cd, rpt.wbs_cd, rpt.pft_cntr_cd
, rpt.vndr_nm, rpt.vndr_nr,rpt.rqstr_usr_id,rpt.exact_typ_cd,rpt.prod_nr,rpt.gl_acct_nr,rpt.mgmt_wbs_cd
,c1.company_code, c1.item,c1.cost_center,c1.created_on,c1.requisitioner,c1.wbs_element,c1.g_l_account,c1.profit_center
From scm_rpt.rpt_pwr_bi_po_dtls_vw rpt
inner join (select purchasing_doc, company_code,item, created_on, requisitioner, cost_center,wbs_element,g_l_account, profit_center from ranked_imt_c1 where rn = 1) c1
on rpt.po_nr = c1.purchasing_doc
and rpt.po_ln_itm = c1.item
where rpt.fscl_yr_nm in ('2021', '2022')''',conn)

Wall time: 37.3 s

In [86]:
df_final

,rpt.ky_po_dt,rpt.cst_cntr_nr,rpt.po_nr,rpt.po_ln_itm,rpt.stts_nm,rpt.cst_cntr_cd,rpt.co_cd,rpt.wbs_cd,rpt.pft_cntr_cd,rpt.vndr_nm,...,rpt.gl_acct_nr,rpt.mgmt_wbs_cd,c1.company_code,c1.item,c1.cost_center,c1.created_on,c1.requisitioner,c1.wbs_element,c1.g_l_account,c1.profit_center
0,2020-04-01,,8500160740,00030,Ordered,,1200,R0101302520001,,MICROFOCUS(US)INC,...,0000510510,R-010130252.0001,1200,00030,,04/01/2020,sbagley,R0101302520001,0000510510,P1120159
1,2020-04-01,,8500160742,00010,Ordered,,1571,R0101086110030,,TECH DATA CORPORATION,...,0000540000,R-010108611.0030,1571,00010,,04/01/2020,rhubenak,R0101086110030,0000540000,P1010169
2,2020-04-02,,8500160804,00020,Ordered,,1202,R0100016370233,,Insight Hardware,...,0000540001,R-010001637.0233,1202,00020,,04/02/2020,dmertens,R0100016370233,0000540001,P1120163
3,2020-04-02,,8500160805,00010,Ordered,,1571,R0100203830021,,Insight Hardware,...,0000510510,R-010020383.0021,1571,00010,,04/02/2020,bgaudreau2,R0100203830021,0000510510,P1000000
4,2020-04-02,,8500160823,00010,Ordered,,1202,S0100168350010,,TENSIONENVELOPE,...,0000561411,S-010016835.0010,1202,00010,,04/02/2020,pbennet4,S0100168350010,0000561411,P1116155
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13024,2020-06-17,,8500167300,00030,Ordered,,1571,R0101293380156,,DELL MARKETING LP,...,0000150040,R-010129338.0156,1571,00030,None,06/17/2020,dvarian,R0101293380156,0000150040,P1013110
13025,2020-06-17,C139500563,8500167302,00010,Ordered,C139500563,1395,0,P9091901,N3 LLC,...,0000504041,None,1395,00010,C139500563,06/17/2020,lpettigrew,None,0000504041,P9091901
13026,2020-06-18,,8500167320,00010,Ordered,,1571,R0100203140366,,Insight Hardware,...,0000540000,R-010020314.0366,1571,00010,None,06/18/2020,scruz7,R0100203140366,0000540000,P1013178
13027,2020-06-24,C157100294,8500167401,00010,Ordered,C157100294,1571,0,P1013179,AnixterInc,...,0000541061,None,1571,00010,C157100294,06/24/2020,jmonroe7,None,0000541061,P1013179
13028,2020-06-29,,8500167500,00010,Ordered,,1571,R0100203670009,,DELL COMPUTER CORPORATION,...,0000510510,R-010020367.0009,1571,00010,None,06/29/2020,dconrad8,R0100203670009,0000510510,P1013178

In [87]:
#Columns renaming
cols = [
"RPT_PO_Number" , "RPT_CostCenter_Number", "RPT_Line_item", "RPT_CostObject_Code", "RPT_Company_Code", "C1_Company_Code","C1_Item","C1_Cost_Center","C1_Created_On" ]

df_1 = df_final.rename(columns = {"rpt.po_nr" : "PO_Number_RPT", "rpt.cst_cntr_nr" : "CostCenter_Number_RPT",
"rpt.po_ln_itm" : "Line_item_RPT", "rpt.stts_nm":"Status_RPT","rpt.cst_cntr_cd" : "CostCenter_Code_RPT","rpt.co_cd" : "Company_Code_RPT",
"rpt.fscl_mth_nm":"Fiscal_month_RPT","rpt.fscl_yr_nm":"Fiscal_year_RPT","rpt.fscl_qtr_nm":"Fiscal_quarter_RPT","rpt.wbs_cd":"WBS_Code_RPT",
"rpt.pft_cntr_cd":"Profit_Center_RPT","rpt.vndr_nm":"Vendor_Number_RPT", "rpt.rqstr_usr_id":"Request_User_ID_RPT","rpt.exact_typ_cd":"Exact_Type_Code_RPT",
"rpt.prod_nr":"Production_Number_RPT","rpt.gl_acct_nr":"GL_Account_RPT","rpt.mgmt_wbs_cd":"Management_WBS_Code_RPT",                          
"rpt.ky_po_dt":"PO_Created_Date_RPT","c1.company_code":"Company_Code_IMT_C1",
"c1.item":"Item_IMT_C1" , "c1.cost_center":"Cost_Center_IMT_C1", "c1.created_on":"Created_On_IMT_C1", "c1.requisitioner":"Requisitioner_IMT_C1", 
"c1.wbs_element":"WBS_Element_IMT_C1","c1.g_l_account":"GL_Account_IMT_C1","c1.profit_center":"Profit_Center_IMT_C1" })
df_1

,PO_Created_Date_RPT,CostCenter_Number_RPT,PO_Number_RPT,Line_item_RPT,Status_RPT,CostCenter_Code_RPT,Company_Code_RPT,WBS_Code_RPT,Profit_Center_RPT,Vendor_Number_RPT,...,GL_Account_RPT,Management_WBS_Code_RPT,Company_Code_IMT_C1,Item_IMT_C1,Cost_Center_IMT_C1,Created_On_IMT_C1,Requisitioner_IMT_C1,WBS_Element_IMT_C1,GL_Account_IMT_C1,Profit_Center_IMT_C1
0,2020-04-01,,8500160740,00030,Ordered,,1200,R0101302520001,,MICROFOCUS(US)INC,...,0000510510,R-010130252.0001,1200,00030,,04/01/2020,sbagley,R0101302520001,0000510510,P1120159
1,2020-04-01,,8500160742,00010,Ordered,,1571,R0101086110030,,TECH DATA CORPORATION,...,0000540000,R-010108611.0030,1571,00010,,04/01/2020,rhubenak,R0101086110030,0000540000,P1010169
2,2020-04-02,,8500160804,00020,Ordered,,1202,R0100016370233,,Insight Hardware,...,0000540001,R-010001637.0233,1202,00020,,04/02/2020,dmertens,R0100016370233,0000540001,P1120163
3,2020-04-02,,8500160805,00010,Ordered,,1571,R0100203830021,,Insight Hardware,...,0000510510,R-010020383.0021,1571,00010,,04/02/2020,bgaudreau2,R0100203830021,0000510510,P1000000
4,2020-04-02,,8500160823,00010,Ordered,,1202,S0100168350010,,TENSIONENVELOPE,...,0000561411,S-010016835.0010,1202,00010,,04/02/2020,pbennet4,S0100168350010,0000561411,P1116155
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13024,2020-06-17,,8500167300,00030,Ordered,,1571,R0101293380156,,DELL MARKETING LP,...,0000150040,R-010129338.0156,1571,00030,None,06/17/2020,dvarian,R0101293380156,0000150040,P1013110
13025,2020-06-17,C139500563,8500167302,00010,Ordered,C139500563,1395,0,P9091901,N3 LLC,...,0000504041,None,1395,00010,C139500563,06/17/2020,lpettigrew,None,0000504041,P9091901
13026,2020-06-18,,8500167320,00010,Ordered,,1571,R0100203140366,,Insight Hardware,...,0000540000,R-010020314.0366,1571,00010,None,06/18/2020,scruz7,R0100203140366,0000540000,P1013178
13027,2020-06-24,C157100294,8500167401,00010,Ordered,C157100294,1571,0,P1013179,AnixterInc,...,0000541061,None,1571,00010,C157100294,06/24/2020,jmonroe7,None,0000541061,P1013179
13028,2020-06-29,,8500167500,00010,Ordered,,1571,R0100203670009,,DELL COMPUTER CORPORATION,...,0000510510,R-010020367.0009,1571,00010,None,06/29/2020,dconrad8,R0100203670009,0000510510,P1013178

In [47]:
df_1.to_csv('SCM_IMT_C1_PO_Output_Latest.csv')

In [88]:
#Missing values
df = (df_1 .replace(r'^\s*$', np.nan, regex=True))
df_missing = df.isnull().sum().to_frame().rename(columns = {0 : "sumofmissingvalues"}).sort_values(by = "sumofmissingvalues", ascending = False)

df_missing ["total_rows"] = len(df)
df_missing_p = df.isnull().sum().to_frame().rename(columns = {0 : "%missingvalues"}).sort_values(by = "%missingvalues", ascending = False)*100/len(df)
df_m = pd.merge(df_missing, df_missing_p, left_index=True, right_index=True)

In [89]:
df_m

                         sumofmissingvalues  total_rows  %missingvalues
Exact_Type_Code_RPT                   13029       13029      100.000000
CostCenter_Number_RPT                 12835       13029       98.511014
CostCenter_Code_RPT                   12835       13029       98.511014
Cost_Center_IMT_C1                    12835       13029       98.511014
Profit_Center_RPT                     12835       13029       98.511014
WBS_Element_IMT_C1                     1786       13029       13.707882
Company_Code_RPT                       1597       13029       12.257272
GL_Account_IMT_C1                      1580       13029       12.126794
Requisitioner_IMT_C1                   1580       13029       12.126794
Profit_Center_IMT_C1                   1580       13029       12.126794
Management_WBS_Code_RPT                 194       13029        1.488986
rpt.vndr_nr                               0       13029        0.000000
Request_User_ID_RPT                       0       13029        0.000000
Vendor_Number_RPT                         0       13029        0.000000
Production_Number_RPT                     0       13029        0.000000
GL_Account_RPT                            0       13029        0.000000
Company_Code_IMT_C1                       0       13029        0.000000
Item_IMT_C1                               0       13029        0.000000
WBS_Code_RPT                              0       13029        0.000000
Created_On_IMT_C1                         0       13029        0.000000
Status_RPT                                0       13029        0.000000
Line_item_RPT                             0       13029        0.000000
PO_Number_RPT                             0       13029        0.000000
PO_Created_Date_RPT                       0       13029        0.000000

In [104]:
#company code comparisions
df["Company_code_consistency"]= np.where(df['Company_Code_RPT']==df['Company_Code_IMT_C1'], 
                                           'match', 'mismatch')
df["Create_on_consistency"]= np.where(df['PO_Created_Date_RPT']==df['Created_On_IMT_C1'], 
                                           'match', 'mismatch')
df["Cost_Center_consistency"]= np.where(df['CostCenter_Code_RPT']==df['Cost_Center_IMT_C1'], 
                                           'match', 'mismatch')
df["Requestor_consistency"]= np.where(df['Request_User_ID_RPT']==df['Requisitioner_IMT_C1'], 
                                           'match', 'mismatch')
df["WBS_consistency"]= np.where(df['WBS_Code_RPT']==df['WBS_Element_IMT_C1'], 
                                           'match', 'mismatch')
df["GL_Account_consistency"]= np.where(df['GL_Account_RPT']==df['GL_Account_IMT_C1'], 
                                           'match', 'mismatch')
df["Profit_Center_consistency"]= np.where(df['Profit_Center_RPT']==df['Profit_Center_IMT_C1'], 
                                           'match', 'mismatch')

In [105]:
df

,PO_Created_Date_RPT,CostCenter_Number_RPT,PO_Number_RPT,Line_item_RPT,Status_RPT,CostCenter_Code_RPT,Company_Code_RPT,WBS_Code_RPT,Profit_Center_RPT,Vendor_Number_RPT,...,WBS_completeness,GL_Account_completeness,Profit_Center_completeness,Company_code_accuracy,Create_on_accuracy,Cost_Center_accuracy,Requestor_accuracy,WBS_accuracy,GL_Account_accuracy,Profit_Center_accuracy
0,2020-04-01,NaN,8500160740,00030,Ordered,NaN,1200,R0101302520001,NaN,MICROFOCUS(US)INC,...,not_missing_in_rpt,not_missing_in_rpt,missing_in_rpt,missing/accurate,not_accurate,not_accurate,missing/accurate,missing/accurate,missing/accurate,missing/accurate
1,2020-04-01,NaN,8500160742,00010,Ordered,NaN,1571,R0101086110030,NaN,TECH DATA CORPORATION,...,not_missing_in_rpt,not_missing_in_rpt,missing_in_rpt,missing/accurate,not_accurate,not_accurate,missing/accurate,missing/accurate,missing/accurate,missing/accurate
2,2020-04-02,NaN,8500160804,00020,Ordered,NaN,1202,R0100016370233,NaN,Insight Hardware,...,not_missing_in_rpt,not_missing_in_rpt,missing_in_rpt,missing/accurate,not_accurate,not_accurate,missing/accurate,missing/accurate,missing/accurate,missing/accurate
3,2020-04-02,NaN,8500160805,00010,Ordered,NaN,1571,R0100203830021,NaN,Insight Hardware,...,not_missing_in_rpt,not_missing_in_rpt,missing_in_rpt,missing/accurate,not_accurate,not_accurate,missing/accurate,missing/accurate,missing/accurate,missing/accurate
4,2020-04-02,NaN,8500160823,00010,Ordered,NaN,1202,S0100168350010,NaN,TENSIONENVELOPE,...,not_missing_in_rpt,not_missing_in_rpt,missing_in_rpt,missing/accurate,not_accurate,not_accurate,missing/accurate,missing/accurate,missing/accurate,missing/accurate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13024,2020-06-17,NaN,8500167300,00030,Ordered,NaN,1571,R0101293380156,NaN,DELL MARKETING LP,...,not_missing_in_rpt,not_missing_in_rpt,missing_in_rpt,missing/accurate,not_accurate,not_accurate,missing/accurate,missing/accurate,missing/accurate,missing/accurate
13025,2020-06-17,C139500563,8500167302,00010,Ordered,C139500563,1395,0,P9091901,N3 LLC,...,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,missing/accurate,not_accurate,missing/accurate,missing/accurate,missing/accurate,missing/accurate,missing/accurate
13026,2020-06-18,NaN,8500167320,00010,Ordered,NaN,1571,R0100203140366,NaN,Insight Hardware,...,not_missing_in_rpt,not_missing_in_rpt,missing_in_rpt,missing/accurate,not_accurate,not_accurate,missing/accurate,missing/accurate,missing/accurate,missing/accurate
13027,2020-06-24,C157100294,8500167401,00010,Ordered,C157100294,1571,0,P1013179,AnixterInc,...,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,missing/accurate,not_accurate,missing/accurate,missing/accurate,missing/accurate,missing/accurate,missing/accurate
13028,2020-06-29,NaN,8500167500,00010,Ordered,NaN,1571,R0100203670009,NaN,DELL COMPUTER CORPORATION,...,not_missing_in_rpt,not_missing_in_rpt,missing_in_rpt,missing/accurate,not_accurate,not_accurate,missing/accurate,missing/accurate,missing/accurate,missing/accurate

In [92]:
df["Company_code_completeness"]= np.where((((df['Company_Code_RPT'].isnull()==True)&( df['Company_Code_IMT_C1'].isnull()!=True))),'missing_in_rpt', 'not_missing_in_rpt')

df["Create_on_completeness"]= np.where((((df['PO_Created_Date_RPT'].isnull()==True)&( df['Created_On_IMT_C1'].isnull()!=True))),'missing_in_rpt', 'not_missing_in_rpt')

df["Cost_Center_completeness"]= np.where((((df['CostCenter_Code_RPT'].isnull()==True)&( df['Cost_Center_IMT_C1'].isnull()!=True))),'missing_in_rpt', 'not_missing_in_rpt')

df["Requestor_completeness"]= np.where((((df['Request_User_ID_RPT'].isnull()==True)&( df['Requisitioner_IMT_C1'].isnull()!=True))),'missing_in_rpt', 'not_missing_in_rpt')

df["WBS_completeness"]= np.where((((df['WBS_Code_RPT'].isnull()==True)&( df['WBS_Element_IMT_C1'].isnull()!=True))),'missing_in_rpt', 'not_missing_in_rpt')

df["GL_Account_completeness"]= np.where((((df['GL_Account_RPT'].isnull()==True)&( df['GL_Account_IMT_C1'].isnull()!=True))),'missing_in_rpt', 'not_missing_in_rpt')

df["Profit_Center_completeness"]= np.where((((df['Profit_Center_RPT'].isnull()==True)&( df['Profit_Center_IMT_C1'].isnull()!=True))),'missing_in_rpt', 'not_missing_in_rpt')

In [93]:
df

,PO_Created_Date_RPT,CostCenter_Number_RPT,PO_Number_RPT,Line_item_RPT,Status_RPT,CostCenter_Code_RPT,Company_Code_RPT,WBS_Code_RPT,Profit_Center_RPT,Vendor_Number_RPT,...,WBS_consistency,GL_Account_consistency,Profit_Center_consistency,Company_code_completeness,Create_on_completeness,Cost_Center_completeness,Requestor_completeness,WBS_completeness,GL_Account_completeness,Profit_Center_completeness
0,2020-04-01,NaN,8500160740,00030,Ordered,NaN,1200,R0101302520001,NaN,MICROFOCUS(US)INC,...,match,match,mismatch,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,missing_in_rpt
1,2020-04-01,NaN,8500160742,00010,Ordered,NaN,1571,R0101086110030,NaN,TECH DATA CORPORATION,...,match,match,mismatch,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,missing_in_rpt
2,2020-04-02,NaN,8500160804,00020,Ordered,NaN,1202,R0100016370233,NaN,Insight Hardware,...,match,match,mismatch,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,missing_in_rpt
3,2020-04-02,NaN,8500160805,00010,Ordered,NaN,1571,R0100203830021,NaN,Insight Hardware,...,match,match,mismatch,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,missing_in_rpt
4,2020-04-02,NaN,8500160823,00010,Ordered,NaN,1202,S0100168350010,NaN,TENSIONENVELOPE,...,match,match,mismatch,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,missing_in_rpt
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13024,2020-06-17,NaN,8500167300,00030,Ordered,NaN,1571,R0101293380156,NaN,DELL MARKETING LP,...,match,match,mismatch,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,missing_in_rpt
13025,2020-06-17,C139500563,8500167302,00010,Ordered,C139500563,1395,0,P9091901,N3 LLC,...,mismatch,match,match,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt
13026,2020-06-18,NaN,8500167320,00010,Ordered,NaN,1571,R0100203140366,NaN,Insight Hardware,...,match,match,mismatch,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,missing_in_rpt
13027,2020-06-24,C157100294,8500167401,00010,Ordered,C157100294,1571,0,P1013179,AnixterInc,...,mismatch,match,match,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt
13028,2020-06-29,NaN,8500167500,00010,Ordered,NaN,1571,R0100203670009,NaN,DELL COMPUTER CORPORATION,...,match,match,mismatch,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,missing_in_rpt

In [94]:
df["Company_code_accuracy"]= np.where(((df['Company_code_completeness']=="not_missing_in_rpt")&(df['Company_Code_RPT']!=df['Company_Code_IMT_C1'])),'not_accurate', 'missing/accurate')

df["Create_on_accuracy"]= np.where(((df['Create_on_completeness']=="not_missing_in_rpt")&(df['PO_Created_Date_RPT']!=df['Created_On_IMT_C1'])),'not_accurate', 'missing/accurate')

df["Cost_Center_accuracy"]= np.where(((df['Cost_Center_completeness']=="not_missing_in_rpt")&(df['CostCenter_Code_RPT']!=df['Cost_Center_IMT_C1'])),'not_accurate', 'missing/accurate')

df["Requestor_accuracy"]= np.where(((df['Request_User_ID_RPT']=="not_missing_in_rpt")&(df['Request_User_ID_RPT']!=df['Requisitioner_IMT_C1'])),'not_accurate', 'missing/accurate')

df["WBS_accuracy"]= np.where(((df['Management_WBS_Code_RPT']=="not_missing_in_rpt")&(df['WBS_Code_RPT']!=df['WBS_Element_IMT_C1'])),'not_accurate', 'missing/accurate')

df["GL_Account_accuracy"]= np.where(((df['GL_Account_RPT']=="not_missing_in_rpt")&(df['GL_Account_RPT']!=df['GL_Account_IMT_C1'])),'not_accurate', 'missing/accurate')

df["Profit_Center_accuracy"]= np.where(((df['Profit_Center_RPT']=="not_missing_in_rpt")&(df['Profit_Center_RPT']!=df['Profit_Center_IMT_C1'])),'not_accurate', 'missing/accurate')

In [95]:
df

,PO_Created_Date_RPT,CostCenter_Number_RPT,PO_Number_RPT,Line_item_RPT,Status_RPT,CostCenter_Code_RPT,Company_Code_RPT,WBS_Code_RPT,Profit_Center_RPT,Vendor_Number_RPT,...,WBS_completeness,GL_Account_completeness,Profit_Center_completeness,Company_code_accuracy,Create_on_accuracy,Cost_Center_accuracy,Requestor_accuracy,WBS_accuracy,GL_Account_accuracy,Profit_Center_accuracy
0,2020-04-01,NaN,8500160740,00030,Ordered,NaN,1200,R0101302520001,NaN,MICROFOCUS(US)INC,...,not_missing_in_rpt,not_missing_in_rpt,missing_in_rpt,missing/accurate,not_accurate,not_accurate,missing/accurate,missing/accurate,missing/accurate,missing/accurate
1,2020-04-01,NaN,8500160742,00010,Ordered,NaN,1571,R0101086110030,NaN,TECH DATA CORPORATION,...,not_missing_in_rpt,not_missing_in_rpt,missing_in_rpt,missing/accurate,not_accurate,not_accurate,missing/accurate,missing/accurate,missing/accurate,missing/accurate
2,2020-04-02,NaN,8500160804,00020,Ordered,NaN,1202,R0100016370233,NaN,Insight Hardware,...,not_missing_in_rpt,not_missing_in_rpt,missing_in_rpt,missing/accurate,not_accurate,not_accurate,missing/accurate,missing/accurate,missing/accurate,missing/accurate
3,2020-04-02,NaN,8500160805,00010,Ordered,NaN,1571,R0100203830021,NaN,Insight Hardware,...,not_missing_in_rpt,not_missing_in_rpt,missing_in_rpt,missing/accurate,not_accurate,not_accurate,missing/accurate,missing/accurate,missing/accurate,missing/accurate
4,2020-04-02,NaN,8500160823,00010,Ordered,NaN,1202,S0100168350010,NaN,TENSIONENVELOPE,...,not_missing_in_rpt,not_missing_in_rpt,missing_in_rpt,missing/accurate,not_accurate,not_accurate,missing/accurate,missing/accurate,missing/accurate,missing/accurate
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13024,2020-06-17,NaN,8500167300,00030,Ordered,NaN,1571,R0101293380156,NaN,DELL MARKETING LP,...,not_missing_in_rpt,not_missing_in_rpt,missing_in_rpt,missing/accurate,not_accurate,not_accurate,missing/accurate,missing/accurate,missing/accurate,missing/accurate
13025,2020-06-17,C139500563,8500167302,00010,Ordered,C139500563,1395,0,P9091901,N3 LLC,...,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,missing/accurate,not_accurate,missing/accurate,missing/accurate,missing/accurate,missing/accurate,missing/accurate
13026,2020-06-18,NaN,8500167320,00010,Ordered,NaN,1571,R0100203140366,NaN,Insight Hardware,...,not_missing_in_rpt,not_missing_in_rpt,missing_in_rpt,missing/accurate,not_accurate,not_accurate,missing/accurate,missing/accurate,missing/accurate,missing/accurate
13027,2020-06-24,C157100294,8500167401,00010,Ordered,C157100294,1571,0,P1013179,AnixterInc,...,not_missing_in_rpt,not_missing_in_rpt,not_missing_in_rpt,missing/accurate,not_accurate,missing/accurate,missing/accurate,missing/accurate,missing/accurate,missing/accurate
13028,2020-06-29,NaN,8500167500,00010,Ordered,NaN,1571,R0100203670009,NaN,DELL COMPUTER CORPORATION,...,not_missing_in_rpt,not_missing_in_rpt,missing_in_rpt,missing/accurate,not_accurate,not_accurate,missing/accurate,missing/accurate,missing/accurate,missing/accurate

In [96]:
df.to_csv('Output_Latest_08032022.csv')

In [106]:
df[['CostCenter_Code_RPT','Cost_Center_IMT_C1','Cost_Center_consistency']]

      CostCenter_Code_RPT Cost_Center_IMT_C1 Cost_Center_consistency
0                     NaN                NaN                mismatch
1                     NaN                NaN                mismatch
2                     NaN                NaN                mismatch
3                     NaN                NaN                mismatch
4                     NaN                NaN                mismatch
...                   ...                ...                     ...
13024                 NaN               None                mismatch
13025          C139500563         C139500563                   match
13026                 NaN               None                mismatch
13027          C157100294         C157100294                   match
13028                 NaN               None                mismatch

[13029 rows x 3 columns]

In [98]:
df[['Profit_Center_RPT','Profit_Center_IMT_C1']]

      Profit_Center_RPT Profit_Center_IMT_C1
0                   NaN             P1120159
1                   NaN             P1010169
2                   NaN             P1120163
3                   NaN             P1000000
4                   NaN             P1116155
...                 ...                  ...
13024               NaN             P1013110
13025          P9091901             P9091901
13026               NaN             P1013178
13027          P1013179             P1013179
13028               NaN             P1013178

[13029 rows x 2 columns]

In [72]:
abc=df[['WBS_Code_RPT','WBS_Element_IMT_C1']]
if abc.iloc[0]['WBS_Code_RPT'] == abc.iloc[0]['WBS_Element_IMT_C1']:
    print('true')

true

In [99]:
Consistency_list=[]

for items in df.columns:
    if "consistency" in items:
        Consistency_list.append(items)
       
df_AUX =df[Consistency_list]
df_AUX = df_AUX.replace("mismatch",np.nan)


df_aux1 = df_AUX.isna().sum().to_frame().rename(columns = {0 : "mismatch_sum"}).sort_values(by = "mismatch_sum", ascending = False)

df_aux1 ["total_rows"] = len(df_AUX)
df_aux2 = df_AUX.isnull().sum().to_frame().rename(columns = {0 : "%mismatch"}).sort_values(by = "%mismatch", ascending = False)*100/len(df_AUX)
df_Consistency = pd.merge(df_aux1, df_aux2, left_index=True, right_index=True)

#df_m["Table_Name"] = df_EDL_1.columns.to_list()[1].split(".")[0]
df_Consistency.to_excel("df_Consistency_RPT_C1.xlsx")
df_Consistency

                           mismatch_sum  total_rows   %mismatch
Create_on_consistency             13029       13029  100.000000
Requestor_consistency             13029       13029  100.000000
Cost_Center_consistency           12835       13029   98.511014
Profit_Center_consistency         12835       13029   98.511014
WBS_consistency                    1791       13029   13.746258
Company_code_consistency           1597       13029   12.257272
GL_Account_consistency             1581       13029   12.134469

In [100]:
Completeness_list=[]

for items in df.columns:
    if "completeness" in items:
        Completeness_list.append(items)
       
df_AUX =df[Completeness_list]
df_AUX = df_AUX.replace("missing_in_rpt",np.nan)


df_aux1 = df_AUX.isna().sum().to_frame().rename(columns = {0 : "missing_in_rpt_sum"}).sort_values(by = "missing_in_rpt_sum", ascending = False)

df_aux1 ["total_rows"] = len(df_AUX)
df_aux2 = df_AUX.isnull().sum().to_frame().rename(columns = {0 : "%missing_in_rpt"}).sort_values(by = "%missing_in_rpt", ascending = False)*100/len(df_AUX)
df_Completeness= pd.merge(df_aux1, df_aux2, left_index=True, right_index=True)

#df_m["Table_Name"] = df_EDL_1.columns.to_list()[1].split(".")[0]
df_Completeness.to_excel("df_Completeness_RPT_C1.xlsx")
df_Completeness

                            missing_in_rpt_sum  total_rows  %missing_in_rpt
Profit_Center_completeness               11255       13029        86.384220
Company_code_completeness                 1597       13029        12.257272
Create_on_completeness                       0       13029         0.000000
Cost_Center_completeness                     0       13029         0.000000
Requestor_completeness                       0       13029         0.000000
WBS_completeness                             0       13029         0.000000
GL_Account_completeness                      0       13029         0.000000

In [101]:
Accuracy_list=[]

for items in df.columns:
    if "accuracy" in items:
        Accuracy_list.append(items)
       
df_AUX =df[Accuracy_list]
df_AUX = df_AUX.replace("not_accurate",np.nan)

df_aux1 = df_AUX.isna().sum().to_frame().rename(columns = {0 : "not_accurate_sum"}).sort_values(by = "not_accurate_sum", ascending = False)

df_aux1 ["total_rows"] = len(df_AUX)
df_aux2 = df_AUX.isnull().sum().to_frame().rename(columns = {0 : "%not_accurate"}).sort_values(by = "%not_accurate", ascending = False)*100/len(df_AUX)
df_Accuracy= pd.merge(df_aux1, df_aux2, left_index=True, right_index=True)

#df_m["Table_Name"] = df_EDL_1.columns.to_list()[1].split(".")[0]
df_Accuracy.to_excel("df_Accuracy_RPT_C1.xlsx")
df_Accuracy

                        not_accurate_sum  total_rows  %not_accurate
Create_on_accuracy                 13029       13029     100.000000
Cost_Center_accuracy               12835       13029      98.511014
Company_code_accuracy                  0       13029       0.000000
Requestor_accuracy                     0       13029       0.000000
WBS_accuracy                           0       13029       0.000000
GL_Account_accuracy                    0       13029       0.000000
Profit_Center_accuracy                 0       13029       0.000000

In [102]:
df_Consistency.columns = df_Completeness.columns = df_Accuracy.columns = ['flag_sum', 'total_rows', '%flags']
df_Output = df_Consistency.append(df_Completeness.append(df_Accuracy))
df_Output.to_excel("df_Output_RPT_C1_08032022.xlsx")
df_Output

                            flag_sum  total_rows      %flags
Create_on_consistency          13029       13029  100.000000
Requestor_consistency          13029       13029  100.000000
Cost_Center_consistency        12835       13029   98.511014
Profit_Center_consistency      12835       13029   98.511014
WBS_consistency                 1791       13029   13.746258
Company_code_consistency        1597       13029   12.257272
GL_Account_consistency          1581       13029   12.134469
Profit_Center_completeness     11255       13029   86.384220
Company_code_completeness       1597       13029   12.257272
Create_on_completeness             0       13029    0.000000
Cost_Center_completeness           0       13029    0.000000
Requestor_completeness             0       13029    0.000000
WBS_completeness                   0       13029    0.000000
GL_Account_completeness            0       13029    0.000000
Create_on_accuracy             13029       13029  100.000000
Cost_Center_accuracy           12835       13029   98.511014
Company_code_accuracy              0       13029    0.000000
Requestor_accuracy                 0       13029    0.000000
WBS_accuracy                       0       13029    0.000000
GL_Account_accuracy                0       13029    0.000000
Profit_Center_accuracy             0       13029    0.000000